### PR TITLE
Do not use pngs for coloured buttons

### PR DESCRIPTION
**Pull request by AbuBaniaz**

### CODE REVIEW

**Comment by Taapat** [comment]
I don't want to drop the option to stylize buttons in the default screens.

**Comment by AbuBaniaz** [comment]
Skinners are free to do what they want. At the moment, the default look your plugin looks like this in ATV.

youtube taapat atv

**Comment by Taapat** [comment]
Or in this skin there will not be problems with buttons for all plugins which screens are not created in skin?

**Comment by AbuBaniaz** [comment]
I don't understand what you mean.

**Comment by Taapat** [comment]
I want to say that this is a skin problem rather than a specific plugin.
Any plugin buttons will be displayed incorrectly if plugin screens is not in this skin.

**Comment by AbuBaniaz** [comment]
They have a skin_default sub-folder which is different to the skin_default standlaone folder

This pull request is to make sure that when your plugin is not skinned in the active skin , your embedded skin will always have rectangular buttons 140x40 or 210x60

**Comment by AbuBaniaz** [comment]
You also keep saying that skin_default sub-folder should not be deleted from the active skin. They will more than likely say the same.

**Comment by Taapat** [comment]
I do not want rectangular buttons 140x40 or 210x60.
I want png with size 140x40 or 210x60 which can be replaced in skin with the same size png, only stylized by skin.

**Comment by Taapat** [comment]
If you do not want to replace them with your own in skin then you should leave the option use images from enigma folder skin_default.
Also on ATV in skin_default.xml is path on buttons in folder skin_default with size 140x40.

**Comment by AbuBaniaz** [comment]
Skin is not the same as folder. Look at the skin-default sub-folder in metrixhd skin. The buttons  are not 140x40. Those are what are used by your plugin, not the ones from standalone folder.

The standlaone folder is only used if teh active skin does not have a sub-folder

**Comment by Taapat** [comment]
That's what I'm saying.
This skin breaks buttons even in screens from skin_default.xml.
It's hiden by adding these screens in skin.
Why do you want to change something in my plugin?
You can hide this skin problem just like with other screens- by adding a plugin in skin.

**Comment by AbuBaniaz** [comment]
If somebody select the skin_default.xml (emeregency skin), it will not use anything from any other skin folders.

You complained about changes in directories affecting your plugin. This is why I submitted the pull request. I shall close it now.

**Pull request closed without merging**
