### PR TITLE
Add option to choose style of VirtualKeyBoard

### PR DESCRIPTION
**Pull request by fairbird**
With this commit we can select and Active Default VirtualKeyBoard for our images using or any Extra VirtualKeyBoard such as this (NewVirtualKeyBoard)
https://github.com/OpenVisionE2/NewVirtualKeyBoard

### CODE REVIEW

**Comment by Taapat** [comment]
Or this NewVirtualKeyBoard used only in some cases and cannot replace Enigma VirtualKeyBoard?
I don't think that it's a good idea introduce for each plugin a config option, so the user in all plugins should switch VirtualKeyBoard.
I think it would be logical to choose VirtualKeyBoard in one place for the whole image.

**Comment by Taapat** [comment]
In fact, what you offer is disable Google Suggestions in a text string.
If you check the code, then you will understand that the plugin does not use the YouTube VirtualKeyBoard style.
The **Virtual** KeyBoard is used to display Google Suggestions in a text string.
Why do you want to disable it?

**Comment by fairbird** [comment]
The screenshots explain the new keyboard feature, which gives you more options than the default keyboard.

**Comment by fairbird** [comment]
Also one more thing ... new option will be solve that error on DreamOS image 
> Apr 20 11:13:08 dm900 enigma2[652]: FATAL!: addTimer must be called from thread 652 but is called from thread 1110

**Comment by Taapat** [comment]
And why do you need a config option to use your KeyBoard?
In the plugin already is used VirtualKeyBoard from Screens.VirtualKeyBoard.
The plugin only adds Google Suggestions in a text string. If you don't need it, just ignore them.


Plugin do not support closed source DreamOS image.
For DreamOS you need exceptions in the your code in any case.
With the config option you do not fix the error. You add the ability to disable the feature that calls it. If you don't know how to fix it, disable this feature in code without the config option.

**Comment by fairbird** [comment]
It is ok ... Never mind my friend ...
You can close this request ..
I will make separate patch for our core OpenVisionE 
https://github.com/OpenVisionE2/openvision-development-platform 

Thank you

**Pull request closed without merging**
