### PR TITLE
YouTubeUi: encode string in _tryStr()

### PR DESCRIPTION
**Pull request by Taapat**

### CODE REVIEW

**Comment by Lishoo** [comment]
Hi, I'v checked the "v = str(get(result)).encode()" with the original code, but there is no difference with the .encode() or without it.

**Comment by Taapat** [comment]
So this change not help you?
You get balnk result?

**Comment by Taapat** [comment]
Maybe you can try the following changes by removing the exception in _tryList().
You will get a GSOD but it should show exactly what is your problem.
```
@@ -787,12 +787,8 @@ def _tryList(result, getter):
	@staticmethod
	def _tryStr(result, getter):
		for get in [getter]:
-			try:
-				v = str(get(result))
-			except:
-				pass
-			else:
-				return v
+			v = str(get(result))
+			return v
		return ''

	def _tryComplStr(self, result, getter, after):```

**Comment by Lishoo** [comment]
I've just tried that 2 lines you suggested and after search there is no GSOD, pressing the info button gives the GSOD the output of the 2 lines is the thumbnails work
test1

and the log
[testlog.txt](https://github.com/Taapat/enigma2-plugin-youtube/files/5503833/testlog.txt)

**Comment by Taapat** [comment]
What is your receiver and image?
I see in the log that you have a very old saurce date and a strange rev.
In the log there are strange python errors.
I think here is some python problem in your image.

**Comment by Lishoo** [comment]
Hi, I know it is old but I don't think I can get anything newer, the receiver is a ADB5800sx (STi7100 SH4) and the system is Graterlia OS (GOS_2016-09-11) Python 2.7.13

The YouTube plugin playback and download works perfect so I wanted to get the title and description working so I'm happy it works, if the thumbnails would work it would be ideal :)

**Comment by Taapat** [comment]
Or for your reciever not exists OpenAtv or Open Vision images?

**Comment by Taapat** [comment]
Can you try this file.
[YouTubeUi.py.zip](https://github.com/Taapat/enigma2-plugin-youtube/files/5504749/YouTubeUi.py.zip)

**Comment by Lishoo** [comment]
> 
> 
> Can you try this file.
> [YouTubeUi.py.zip](https://github.com/Taapat/enigma2-plugin-youtube/files/5504749/YouTubeUi.py.zip)
I don't see any change
efect1
efect2

**Comment by Taapat** [comment]
And this is a different realization of your proposed change.
[YouTubeUi.py.zip](https://github.com/Taapat/enigma2-plugin-youtube/files/5504864/YouTubeUi.py.zip)

**Comment by Lishoo** [comment]
Unfortunately no change :(
My string function can't handle the Unicode characters, the titles without the Unicode chars are displayed property, but with them it can't get the ['snippet']['title'] the get['snippet'] passes the result.
Maybe it because the six python library?

**Comment by Lishoo** [comment]
Calling this function:

```
	@staticmethod
	def _tryStr(getter):
		try:
			v = str(getter)
		except:
			pass
		else:
			return v
		return ''
```
like this works perfect

`self._tryStr(result['snippet']['title'].encode('utf-8', 'ignore')),  # Title`

**Comment by Lishoo** [comment]
```
	@staticmethod
	def _tryStr(result, getter):
		for get in [getter]:
			try:
				v = str(get(result).encode('utf-8', 'ignore'))
			except:
				pass
			else:
				return v
		return ''
```
This fixes the title and description display.

**Comment by Taapat** [comment]
The idea of _tryStr() is to return a string even if the object is not a string.
I don't remember exactly where, but somewhere there was a problem with it.
encode() can only be used for a string object.
With your proposed changes you can remove str() here because if encode() is working it means that the object is already a string.
This means that converting to a string with your proposed changes will not work here.


As I wrote above it looks like your image have problems with the string function.
You can try this, but it is actually an exception for your image:
```
	def _tryStr(result, getter):
		v = ''
		for get in [getter]:
			try:
				v = str(get(result))
			except:
				try:
					v = get(result).encode('utf-8', 'ignore')
				except:
					pass
		return v
```

**Comment by Lishoo** [comment]
Yes that works perfect, thanks.
fix1
fix2

**Comment by Taapat** [comment]
https://github.com/Taapat/enigma2-plugin-youtube/commit/c9153d500c9c9895e74790e31b088afd040a1fcd

**Pull request closed without merging**
